[task1a1b] added imdb_movie_info_crwaler module
Lucas5Lucas/drupalpractice pull request #1
Opened 2017-07-04 14:25 UTC by Lucas5Lucas

2017-07-04 14:47 UTC, carsten-propeople requested changes

2017-07-04 14:47 UTC, carsten-propeople commented on drupal/web/sites/all/modules/costum/imdb movie info crawler/imdb_movie_info_crawler.module
> +    $items['Imdb_Crawler'] = array(
use small letters

2017-07-04 14:47 UTC, carsten-propeople commented on drupal/web/sites/all/modules/costum/imdb movie info crawler/imdb_movie_info_crawler.module
> +    $items['Movie_Info'] = array(
same here

2017-07-04 14:47 UTC, carsten-propeople commented on drupal/web/sites/all/modules/costum/imdb movie info crawler/imdb_movie_info_crawler.module
> +      'access callback' => TRUE,
add access checks

2017-07-04 14:47 UTC, carsten-propeople commented on drupal/web/sites/all/modules/costum/imdb movie info crawler/imdb_movie_info_crawler.module
> +      'access callback' => TRUE,
add access checks

2017-07-04 14:47 UTC, carsten-propeople commented on drupal/web/sites/all/modules/costum/imdb movie info crawler/imdb_movie_info_crawler.module
> +      '#description' => 'Enter the imdb movie link here',
put t()

2017-07-04 14:47 UTC, carsten-propeople commented on drupal/web/sites/all/modules/costum/imdb movie info crawler/imdb_movie_info_crawler.module
> +        $form_state['rebuild'] = TRUE;
not needed

2017-07-04 14:47 UTC, carsten-propeople commented on drupal/web/sites/all/modules/costum/imdb movie info crawler/imdb_movie_info_crawler.module
> + * Implements hook_form_submit().
kein hook...

2017-07-04 14:47 UTC, carsten-propeople commented on drupal/web/sites/all/modules/costum/imdb movie info crawler/imdb_movie_info_crawler.module
> +    $movie_infos = get_imdb_movie_infos($form_state['values']['movie_url']);
remanem get_imdb_movie_infos to imdb_movie_info_crwaler_fetch_infos()

2017-07-04 14:47 UTC, carsten-propeople commented on drupal/web/sites/all/modules/costum/imdb movie info crawler/imdb_movie_info_crawler.module
> +    drupal_goto("Movie_Info");
Hinweise:

1) drupal_goto('url', array('query' => array('title' => $movie_infos['title'], ))
2) SeSSION
3) write result to db -> redirect with ID -> on new page load from db

4) Goto() -> $form_state['redirect'] ersetzten.

2017-07-04 14:47 UTC, carsten-propeople commented on drupal/web/sites/all/modules/costum/imdb movie info crawler/imdb_movie_info_crawler.module
> +    $movie_infos = array(
add checks for session var,

2017-07-04 14:47 UTC, carsten-propeople commented on drupal/web/sites/all/modules/costum/imdb movie info crawler/imdb_movie_info_crawler.module
> +      'plot' => $_SESSION['movie_infos']['plot'],
eg.: 'plot' = !empty($_SESSION['movie_infos']['plot']) ? $_SESSION['movie_infos']['plot'] : '';

2017-07-04 14:47 UTC, carsten-propeople commented on drupal/web/sites/all/modules/costum/imdb movie info crawler/imdb_movie_info_crawler.module
> +    $page['Movie_Info'] = [
lower case

2017-07-04 14:47 UTC, carsten-propeople commented on drupal/web/sites/all/modules/costum/imdb movie info crawler/imdb_movie_info_crawler.module
> +    //extracts movie title from page
coding convention
// Extracts movie tile from page.

2017-07-04 14:47 UTC, carsten-propeople commented on drupal/web/sites/all/modules/costum/imdb movie info crawler/imdb_movie_info_crawler.module
> +    @$movie_infos = array(
remove @

2017-07-04 14:47 UTC, carsten-propeople commented on drupal/web/sites/all/modules/costum/imdb movie info crawler/imdb_movie_info_crawler.module
> +    @$homepage = file_get_contents($url);
remove @

2017-07-04 14:47 UTC, carsten-propeople commented on drupal/web/sites/all/modules/costum/imdb movie info crawler/imdb_movie_info_crawler.module
> +        'variables' => array('infos' => []),
add defaults

2017-07-04 14:47 UTC, carsten-propeople commented on drupal/web/sites/all/modules/costum/imdb movie info crawler/templates/movie_infos.tpl.php
> +<h1><?php print $infos['title']; ?></h1>
add check

2017-07-04 14:47 UTC, carsten-propeople commented on drupal/web/sites/all/modules/costum/imdb movie info crawler/templates/movie_infos.tpl.php
> +    <a href="<?php print $infos['posterlink']; ?>" >
for links use l function

2017-07-04 14:47 UTC, carsten-propeople commented on drupal/web/sites/all/modules/costum/imdb movie info crawler/templates/movie_infos.tpl.php
> +<h1><a style="color: red; text-decoration: underline; font-size: 200%;" href='./Imdb_Crawler'>again</a></h1>
remove inline styles

2017-07-04 14:47 UTC, carsten-propeople commented on nbproject/private/private.xml
>  <?xml version="1.0" encoding="UTF-8"?>
add this file to .gitignore

2017-07-11 08:31 UTC, carsten-propeople requested changes

2017-07-11 08:31 UTC, carsten-propeople commented on drupal/web/sites/all/modules/costum/imdb movie info crawler/imdb_movie_info_crawler.module
> +        form_set_error("movie_url", "Please enter a valid url!");
t() is missing

2017-07-11 08:31 UTC, carsten-propeople commented on drupal/web/sites/all/modules/costum/imdb movie info crawler/templates/movie_infos.tpl.php
> +<h1><?php print !empty($infos['title']) ? $infos['title'] : "No title found!" ; ?></h1>
t() is missing

2017-07-11 08:31 UTC, carsten-propeople commented on drupal/web/sites/all/modules/costum/imdb movie info crawler/templates/movie_infos.tpl.php
> +<h1><?php print l("AGAIN", "/imdb_crawler", array('attributes' => array('class' => 'back-link'))); ?></h1>
t() is missing

2017-07-11 08:31 UTC, carsten-propeople commented on nbproject/private/private.xml
>      <editor-bookmarks xmlns="http://www.netbeans.org/ns/editor-bookmarks/2" lastBookmarkId="0"/>
this file needs to be removed from the index

2017-07-11 09:02 UTC, Lucas5Lucas commented
@carsten-propeople changes have been made

2017-07-11 09:47 UTC, merged